# Generated by Django 4.2.9 on 2024-02-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourtravelapp', '0003_tourcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourcart',
            old_name='qty',
            new_name='qty_adult',
        ),
        migrations.AddField(
            model_name='tourcart',
            name='qty_child',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
